################################################################################
# Valid colors: AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN,#
# DARK_PURPLE, DARK_RED, GOLD, GRAY, GREEN, LIGHT_PURPLE, RED, WHITE, YELLOW   #
#                                                                              #
# Always use UPPERCASE for color names.                                        #
#                                                                              #
# Add as many groups you want.                                                 #
################################################################################

groups:
  admin:
    permission: cnt.admin
    color: DARK_RED
  mod:
    permission: cnt.mod
    color: GREEN